### ISSUE TITLE
(BUG ?) Engineers with more than 1 Turret or Dispenser up at a time

### ISSUE THREAD

**Issue by Vaygrim** [rafradek/Mods#13]
Minecraft 1.12.2
Forge 2544
Rafradek_tf2_weapons-1.12-2.3.6.16-universal

"Engineer Nests" are a fairly big issue in the above listed version of the mod. We are getting a single Engineer setup 3 Turrets and 2 Dispensers all by themselves. Even with something like a Direct Hit or Grenade Launcher at your disposal, that much firepower from auto-targeting turrets is just madness. Can we please see a hard limit of 1 Turret and 1 Dispenser per NPC Engineer be put into effect?

**Comment by rafradek** [comment]
I know it seems unfair, but it is common that only one engineer is alive and the rest is missing or dead

**Comment by Vaygrim** [comment]
No I've SEEN an Engineer (on the same team I was) drop Turret-1 and upgrade it. Then Turret-2 and upgrade it... then Turret-3 and upgrade it.

This isn't an incident of 3 engineers, 3 turrets, and 2 of the engie's died.
