### ISSUE TITLE
"Exception in server tick loop" (Crash on Server Start)

### ISSUE THREAD

**Issue by Vaygrim** [rafradek/Mods#17]
Latest version of "TF2 Stuff" causes a crash during startup of the server. Happens immediately:

[crash-2017-12-19_19.56.36-server.txt](https://github.com/rafradek/Mods/files/1573066/crash-2017-12-19_19.56.36-server.txt)

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   ForgelinPlugin (Forgelin-1.6.0.jar)
>   AstralCore (astralsorcery-1.12.2-1.8.4.jar)
>   ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.jar)
>   LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
>   CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
> Contact their authors BEFORE contacting forge
> 
> // On the bright side, I bought you a teddy bear!
> 
> Time: 12/19/17 7:56 PM
> Description: Exception in server tick loop
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from TF2 Stuff Mod (rafradek_tf2_weapons)
> Caused by: java.lang.NoClassDefFoundError: rafradek/TF2weapons/characters/EntityStatue$1
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
> 	at java.lang.Class.getConstructor0(Class.java:3075)
> 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findConstructor(ReflectionHelper.java:254)
> 	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.<init>(EntityEntryBuilder.java:284)
> 	at net.minecraftforge.fml.common.registry.EntityEntry$1.<init>(EntityEntry.java:46)
> 	at net.minecraftforge.fml.common.registry.EntityEntry.init(EntityEntry.java:46)
> 	at net.minecraftforge.fml.common.registry.EntityEntry.<init>(EntityEntry.java:40)
> 	at net.minecraftforge.fml.common.registry.EntityRegistry.doModEntityRegistration(EntityRegistry.java:183)
> 	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:151)
> 	at rafradek.TF2weapons.TF2weapons.preinit(TF2weapons.java:531)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
> 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
> 	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.ClassNotFoundException: rafradek.TF2weapons.characters.EntityStatue$1
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 47 more
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityOtherPlayerMP
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
> 	... 49 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityOtherPlayerMP
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 53 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Linux (amd64) version 4.4.0-98-generic
> 	Java Version: 1.8.0_111, Oracle Corporation
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 3611040432 bytes (3443 MB) / 4159438848 bytes (3966 MB) up to 4159438848 bytes (3966 MB)
> 	JVM Flags: 5 total; -Xms4000M -Xmx4000M -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.1.2566 91 mods loaded, 91 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID                             | Version           | Source                                          | Signature                                |
> 	|:----- |:------------------------------ |:----------------- |:----------------------------------------------- |:---------------------------------------- |
> 	| UCH   | minecraft                      | 1.12.2            | minecraft.jar                                   | None                                     |
> 	| UCH   | mcp                            | 9.42              | minecraft.jar                                   | None                                     |
> 	| UCH   | FML                            | 8.0.99.99         | forge-1.12.2-14.23.1.2566-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCH   | forge                          | 14.23.1.2566      | forge-1.12.2-14.23.1.2566-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCH   | appliedenergistics2            | rv5-stable-3      | appliedenergistics2-rv5-stable-3.jar            | None                                     |
> 	| UCH   | bdlib                          | 1.14.3.10         | bdlib-1.14.3.10-mc1.12.2.jar                    | None                                     |
> 	| UCH   | ae2stuff                       | 0.7.0.4           | ae2stuff-0.7.0.4-mc1.12.2.jar                   | None                                     |
> 	| UCH   | akashictome                    | 1.2-10            | AkashicTome-1.2-10.jar                          | None                                     |
> 	| UCH   | tammodized                     | 0.15.3            | TamModized-1.12.1-0.15.3.jar                    | None                                     |
> 	| UCH   | aov                            | 0.8.2             | AoV-1.12-0.8.2.jar                              | None                                     |
> 	| UCH   | crafttweaker                   | 4.0.10            | CraftTweaker2-1.12-4.0.10.jar                   | None                                     |
> 	| UCH   | mtlib                          | @VERSION@         | MTLib-3.0.1.jar                                 | None                                     |
> 	| UCH   | modtweaker                     | 4.0.5             | modtweaker-4.0.5.jar                            | None                                     |
> 	| UCH   | jei                            | 4.8.5.138         | jei_1.12.2-4.8.5.138.jar                        | None                                     |
> 	| UCH   | appleskin                      | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
> 	| UCH   | astralsorcery                  | 1.8.4             | astralsorcery-1.12.2-1.8.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
> 	| UCH   | autoreglib                     | 1.3-15            | AutoRegLib-1.3-15.jar                           | None                                     |
> 	| UCH   | badwithernocookiereloaded      | 1.12.2-2.12       | badwithernocookiereloaded-1.12.2-2.12.jar       | None                                     |
> 	| UCH   | base                           | 3.4.2             | base-1.12-3.4.2.jar                             | None                                     |
> 	| UCH   | baubles                        | 1.5.1             | Baubles-1.12-1.5.1.jar                          | None                                     |
> 	| UCH   | bonsaitrees                    | 1.0.1             | bonsaitrees-1.0.1-b56.jar                       | None                                     |
> 	| UCH   | bookshelf                      | 2.3.511           | Bookshelf-1.12.2-2.3.511.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCH   | cyclopscore                    | 0.10.24           | CyclopsCore-1.12.2-0.10.24.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| UCH   | capabilityproxy                | 2.0.0             | CapabilityProxy-1.12.2-2.0.0.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| UCH   | chisel                         | MC1.12-0.1.0.23   | Chisel-MC1.12-0.1.0.23.jar                      | None                                     |
> 	| UCH   | chiselsandbits                 | 14.11             | chiselsandbits-14.11.jar                        | None                                     |
> 	| UCH   | codechickenlib                 | 3.1.5.331         | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| UCH   | redstoneflux                   | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
> 	| UCH   | cofhcore                       | 4.3.7             | CoFHCore-1.12.2-4.3.7.25-universal.jar          | None                                     |
> 	| UCH   | cofhworld                      | 1.0.2             | CoFHWorld-1.12.2-1.0.2.10-universal.jar         | None                                     |
> 	| UCH   | morpheus                       | 1.12-3.3.2        | Morpheus-1.12-3.3.2.jar                         | None                                     |
> 	| UCH   | comforts                       | 1.1.0             | comforts-1.12.2-1.1.0.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
> 	| UCH   | commoncapabilities             | 1.4.0             | CommonCapabilities-1.12-1.4.0.jar               | None                                     |
> 	| UCH   | compfac                        | 1.1.0             | compfac-1.2.5.jar                               | None                                     |
> 	| UCH   | contenttweaker                 | 1.12-4.2.0        | ContentTweaker-1.12-4.2.0.jar                   | None                                     |
> 	| UCH   | corail_pillar_extension_chisel | 4.0.0             | corail_pillar_extension_chisel-4.0.0-1.12.jar   | None                                     |
> 	| UCH   | crafttweakerjei                | 2.0.0             | CraftTweaker2-1.12-4.0.10.jar                   | None                                     |
> 	| UCH   | p455w0rdslib                   | 2.0.24            | p455w0rdslib-1.12-2.0.24.jar                    | None                                     |
> 	| UCH   | theoneprobe                    | 1.4.19            | theoneprobe-1.12-1.4.19.jar                     | None                                     |
> 	| UCH   | danknull                       | 1.2.19            | DankNull-1.12-1.2.19.jar                        | None                                     |
> 	| UCH   | darkutils                      | 1.7.181           | DarkUtils-1.12.2-1.7.181.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCH   | deathcounter                   | 1.0.0             | DeathCounter-1.12.1-1.0.0.jar                   | None                                     |
> 	| UCH   | everlastingabilities           | 1.3.9             | EverlastingAbilities-1.12.2-1.3.9.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| UCH   | extracells                     | 2.5.9             | ExtraCells-1.12.2-2.5.9a45.jar                  | None                                     |
> 	| UCH   | flatcoloredblocks              | mc1.12-6.6        | flatcoloredblocks-mc1.12-6.6.jar                | None                                     |
> 	| UCH   | forgelin                       | 1.6.0             | Forgelin-1.6.0.jar                              | None                                     |
> 	| UCH   | gravestone                     | 1.10.0            | gravestone-1.10.0.jar                           | None                                     |
> 	| UCH   | harvest                        | 1.12-1.2.6-18     | Harvest-1.12-1.2.6-18.jar                       | None                                     |
> 	| UCH   | incontrol                      | 3.6.3             | incontrol-1.12-3.6.3.jar                        | None                                     |
> 	| UCH   | teslacorelib                   | 1.0.12            | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
> 	| UCH   | industrialforegoing            | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.6.3-107.jar        | None                                     |
> 	| UCH   | industrialmeat                 | 1.12-1.0.2        | industrialmeat-1.12-1.0.2.jar                   | None                                     |
> 	| UCH   | integrateddynamics             | 0.9.9             | IntegratedDynamics-1.12.2-0.9.9.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| UCH   | integrateddynamicscompat       | 1.0.0             | IntegratedDynamics-1.12.2-0.9.9.jar             | None                                     |
> 	| UCH   | integratedtunnels              | 1.3.6             | IntegratedTunnels-1.12.2-1.3.6.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
> 	| UCH   | inventorysorter                | 1.12.4+52         | inventorysorter-1.12.2-1.12.4+52.jar            | None                                     |
> 	| UCH   | ironbackpacks                  | 1.12.2-3.0.2-3    | IronBackpacks-1.12.2-3.0.2-3.jar                | None                                     |
> 	| UCH   | ironchest                      | 1.12.2-7.0.34.820 | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
> 	| UCH   | journeymap                     | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                     | None                                     |
> 	| UCH   | justenoughbuttons              | 1.12-1.2          | justenoughbuttons-1.12.2-1.2.2-5.jar            | None                                     |
> 	| UCH   | lostcities                     | 1.0.2             | lostcities-1.12-1.0.2.jar                       | None                                     |
> 	| UCH   | lostsouls                      | 1.0.0             | lostsouls-1.12-1.0.0.jar                        | None                                     |
> 	| UCH   | meecreeps                      | 1.0.1             | meecreeps-1.12-1.0.1.jar                        | None                                     |
> 	| UCH   | netherportalfix                | 5.3.13            | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
> 	| UCH   | nice                           | 0.1.0             | nice-1.12-0.1.0.jar                             | None                                     |
> 	| UCH   | notenoughwands                 | 1.5.9             | notenoughwands-1.12-1.5.9.jar                   | None                                     |
> 	| UCH   | thermalfoundation              | 2.3.7             | ThermalFoundation-1.12.2-2.3.7.18-universal.jar | None                                     |
> 	| UCH   | thermalexpansion               | 5.3.7             | ThermalExpansion-1.12.2-5.3.7.31-universal.jar  | None                                     |
> 	| UCH   | omlib                          | 3.0.0-131         | omlib-1.12.2-3.0.0-131.jar                      | None                                     |
> 	| UCH   | openglider                     | @VERSION@         | OpenGlider-1.12.1-1.1.0.jar                     | None                                     |
> 	| UCH   | openmodularturrets             | 3.0.0-227         | openmodularturrets-1.12.2-3.0.0-227.jar         | None                                     |
> 	| UCH   | clayspawn                      | 1.12a             | Pam's ClaySpawn 1.12a.jar                       | None                                     |
> 	| UCE   | rafradek_tf2_weapons           | 1.2.3             | rafradek_tf2_weapons-1.12-1.2.3.jar             | None                                     |
> 	| UCH   | rangedpumps                    | 0.5               | rangedpumps-0.5.jar                             | None                                     |
> 	| UCH   | redstonearsenal                | 2.3.7             | RedstoneArsenal-1.12.2-2.3.7.18-universal.jar   | None                                     |
> 	| UCH   | xreliquary                     | 1.12.2-1.3.4.728  | Reliquary-1.12.2-1.3.4.728.jar                  | None                                     |
> 	| UCH   | rftools                        | 7.15              | rftools-1.12-7.15.jar                           | None                                     |
> 	| UCH   | roost                          | 1.2.0             | roost-1.12-1.2.0.jar                            | None                                     |
> 	| UCH   | scrap                          | 1.4.2             | scrap-1.4.2.jar                                 | None                                     |
> 	| UCH   | storagenetwork                 | 1.12.1-1.1.1      | SimpleStorageNetwork-1.12.1-1.1.1.jar           | None                                     |
> 	| UCH   | thermalcultivation             | 0.1.2             | ThermalCultivation-1.12.2-0.1.2.8-universal.jar | None                                     |
> 	| UCH   | thermaldynamics                | 2.3.7             | ThermalDynamics-1.12.2-2.3.7.14-universal.jar   | None                                     |
> 	| UCH   | tp                             | 1.12              | tinyprogressions-1.12-3.2.10 - Beta.jar         | None                                     |
> 	| UCH   | tinyreactors                   | 1.12              | tinyreactors-1.12-0.5.3.jar                     | None                                     |
> 	| UCH   | topaddons                      | 1.12.2-1.2.1      | topaddons-1.12.2-1.2.1.jar                      | None                                     |
> 	| UCH   | tothebatpoles                  | 1.12-1.1.0.0      | tothebatpoles-1.12-1.1.0.0.jar                  | None                                     |
> 	| UCH   | trashslot                      | 8.4.6             | TrashSlot_1.12.1-8.4.6.jar                      | None                                     |
> 	| UCH   | treechopper                    | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                    | None                                     |
> 	| UCH   | waystones                      | 4.0.17            | Waystones_1.12.1-4.0.17.jar                     | None                                     |
> 	| UCH   | corail_pillar                  | 4.0.0             | corail_pillar-4.0.0-1.12.jar                    | None                                     |
> 	| UCH   | teslacorelib_registries        | 1.0.12            | tesla-core-lib-1.12-1.0.12.jar                  | None                                     |
> 
> 	Loaded coremods (and transformers): 
> ForgelinPlugin (Forgelin-1.6.0.jar)
>   
> AstralCore (astralsorcery-1.12.2-1.8.4.jar)
>   
> ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.jar)
>   c4.comforts.asm.SleepTransformer
> LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
>   lumien.resourceloader.asm.ClassTransformer
> CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
>   team.chisel.ctm.client.asm.CTMTransformer
> 	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
> 	List of loaded APIs: 
> 		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-3.jar
> 		* Base|API (1.0.0) from base-1.12-3.4.2.jar
> 		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.1.jar
> 		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
> 		* BotaniaAPI (79) from AkashicTome-1.2-10.jar
> 		* Chisel-API (0.0.1) from Chisel-MC1.12-0.1.0.23.jar
> 		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.1.0.23.jar
> 		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.11.jar
> 		* cofhapi (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
> 		* cofhapi|block (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
> 		* cofhapi|core (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
> 		* cofhapi|item (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
> 		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
> 		* cofhapi|util (2.0.0) from CoFHCore-1.12.2-4.3.7.25-universal.jar
> 		* commoncapabilities|api (0.0.1) from CommonCapabilities-1.12-1.4.0.jar
> 		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.9.jar
> 		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.9.jar
> 		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.9.jar
> 		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.9.jar
> 		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.9.jar
> 		* industrialforegoingapi (3) from industrialforegoing-1.12.2-1.6.3-107.jar
> 		* integrateddynamics|api (0.2.0) from IntegratedDynamics-1.12.2-0.9.9.jar
> 		* jeresources|API (0.8.6.28) from JustEnoughResources-1.12.2-0.8.6.28.jar
> 		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
> 		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
> 		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
> 		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
> 		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
> 		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.138.jar
> 		* mcjtylib_ng (2.5.0) from mcjtylib-1.12-2.5.0.jar
> 		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
> 		* Open Glider|API (0.1) from OpenGlider-1.12.1-1.1.0.jar
> 		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.24.jar
> 		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.19.jar
> 	Profiler Position: N/A (disabled)
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server (map_server.txt)

**Comment by rafradek** [comment]
Should be fixed now
