### ISSUE TITLE
Team Picking *feature request*

### ISSUE THREAD

**Issue by m1jordanallen** [rafradek/Mods#20]
First and foremost this mod is mind blowing.  Its amazing how much you have been able to capture the spirit of TF2. And just about every nuance of TF2 is in the mod. 10/10.

I was wondering if there is a way to force a team pick.  Ideally, you start the world and get prompted to pick a team instead of visiting saxton. Some of my users of the pack are avoiding picking a team so they never get targeted.  Id love to force them into a team as I want your mod to be a focus of challenge and being able to avoid picking a team (while also avoiding trading with saxton at all) lets them almost bypass the entire concept.  

Ideally this is a config for pack makers that do not share my opinion :)

Useless info about the pack:
This request is for the Madpack 4 pack, made by myself and JonBams in case you were wondering.  We heavily use your mod almost daily on stream at Jon's channel. Again, this mod quickly became a favorite for both of us. Great work and thank you for considering the feature :)

**Comment by rafradek** [comment]
Teams are vanilla scoreboard teams, so you would have to execute team join command: /scoreboard teams  join

**Comment by m1jordanallen** [comment]
Okay. I will try to use that info to force users to pick a team on world join through maybe a different mod.
