### ISSUE TITLE
[Issue] Australium statues........

### ISSUE THREAD

**Issue by BadLucKWyvern** [rafradek/Mods#36]
rafradek_tf2_weapons-1.12.2-1.4.1b
Australium statues are a total mess, theres no point to upgrade a weapon to the Australium, Exepted if you want to be invaded by golden statues that you have to destroy with a punch one by one (don't forget if you are covering it in dirt etc, it will stay forever
Australum statues are even blocking bullets and other projectile types
Why not creating a single australium death animation wich is dissapearing after 2 or 3 seconds ? Why not creating a config option wich allow us to disable those statues ?

**Comment by rafradek** [comment]
Australium statues should disappear after some time now, it was bugged and it never disappeared
