### ISSUE TITLE
[crash] Mercenary crashes when reloading

### ISSUE THREAD

**Issue by Mrbysco** [rafradek/Mods#41]
TF2 Stuff Version: V1.4.9

How: I created a world and it instantly crashed with an arrayoutofbound crash.

Crashlog: https://pastebin.com/SCDBSkxR

**Comment by rafradek** [comment]
This should be fixed now

**Comment by Mrbysco** [comment]
Just wondering. Is there going to be a version marked as release soon? Because I tried installing TF2 Stuff in a Twitch pack and it installed the last Release. (which was 1.3.8.2) So I had to manually update.
