### ISSUE TITLE
[suggestion] Command for ending invasion

### ISSUE THREAD

**Issue by Mrbysco** [rafradek/Mods#42]
My friends and I are playing in a custom modpack and the robot invasion got bugged out to the point it was still going on while no mobs were spawning. 

I would like to suggest a command for ending invasions.

**Comment by rafradek** [comment]
Invasions end automatically after a day or even less. But would you like to give more more detail on this i would be thankful

**Comment by Mrbysco** [comment]
Well. For us the invasion bar stayed after a day or 2. (People were sleeping with morpheus)
Nothing was spawning yet the invasion bar stayed. So we thought it was bugged.

**Comment by rafradek** [comment]
yeah, then it might be, considering i never tested this with other people on a server. But if that happens, i guess the invasion is actually done on the server and after a reconnect the bar should be gone

**Comment by Mrbysco** [comment]
I think one of the mods we got cleared the hostile mobs for some reason and borked it.

**Comment by Mrbysco** [comment]
We removed the mod we suspected of borking it and nope. It's still borked.

Do they only spawn at night? because they stopped spawning and even after rejoining the bar is still there.

Basically we can't do the event properly.

**Comment by Mrbysco** [comment]
Basically we can't do the events as they are broken for us.

**Comment by rafradek** [comment]
Beginner difficulty is bugged, use higher difficulty instead

**Comment by rafradek** [comment]
I guess this is fixed im closing this
