### ISSUE TITLE
[Urgent Issue] Australium weapon causing player to be unable to join server after dying

### ISSUE THREAD

**Issue by Mrbysco** [rafradek/Mods#46]
In a modpack I play in someone was like "Oh kill me with this weapon so I can have a statue of myself"
Well... After the dude killed the other dude they both crashed and are unable to join the server again.
![afbeelding](https://user-images.githubusercontent.com/9308260/50055220-274cd600-014c-11e9-9d00-307b389ad278.png)
They get greeted by this message when joining.
I believe the statues are the cause.

In the past another player got the same crash and I had to completely get rid of his player data to fix his issue.

**Comment by Mrbysco** [comment]
Any way we can get the players back on the server without wiping their player data.

**Comment by Mrbysco** [comment]
At this point the TF2 mod has caused so many issues that we just plan on removing it all together as it's way too buggy.

**Comment by Mrbysco** [comment]
The other user which player data I had to clear out killed himself with a Australium grenade launcher and got a statue of himself. Then he was booted of and forever bugged until the data was cleared.

**Comment by scopiplays** [comment]
I was able to recreate this and examine the playerdata using NBTExplorer.  The statue itself contains an exact copy of the nbt tree of the deceased player, including all inventory items and attributes.  Having that statue in your inventory will double the size of your player.dat  

Maybe this is enabled so the mod author can display the armor?

**Comment by scopiplays** [comment]
quick 'fix' to allow players back online is a repeating command block in a loaded chunk running a /kill @e[Item] and then load the chunk with the statue(s).

[08:13:42] [Server thread/INFO] [minecraft/DedicatedServer]: [@: Killed item.item.statue]

**Comment by rafradek** [comment]
Should be fixed now, at least in a way that the statue would not appear at all if it was about to crash
