### ISSUE TITLE
Server crash when launched.

### ISSUE THREAD

**Issue by Jumper128** [rafradek/Mods#48]
Whenever i launch my server with this mod installed, It crashes, I've tried removing all the mods but tf2, It stills crashing, I also have tried updating forge and it keeps happening, I'm a bit basic on this thing about servers so i must be missing something maybe, Here's the log

[latest.log](https://github.com/rafradek/Mods/files/2790316/latest.log)

BTW: Sorry for my bad english.

**Comment by Jumper128** [comment]
i forgot to mention that i'm using 1.8 mc version.

**Comment by rafradek** [comment]
I can't help, minecraft 1.8 is long time not supported
