### ISSUE TITLE
[Issue] Sound and render issue on multiplayer for upgraded sentry

### ISSUE THREAD

**Issue by DarkwarriorJ** [rafradek/Mods#50]
https://paste.dimdev.org/itogiyozer.mccrash

**Comment by DarkwarriorJ** [comment]
This is after the more powerful/Machina bullets upgrade

**Comment by rafradek** [comment]
i hope this is fixed now, you should check it

**Comment by DarkwarriorJ** [comment]
Confirmed fixed!
