### ISSUE TITLE
[Issue] Unsynced upgrade GUI; Multiplayer firing rate issues.

### ISSUE THREAD

**Issue by DarkwarriorJ** [rafradek/Mods#51]
As per the title; if the server has one upgrade multiplier and the client has another, the client sees its own numbers when really the server's numbers apply.

Similarly, there's a strange issue between client and serverside now where it  completely ignores the firing rate - it just fires as fast as it wants, which is way too fast.

**Comment by rafradek** [comment]
About the first one, it is fixed
I can't reproduce the second issue, i might need some more data for that

**Comment by DarkwarriorJ** [comment]
The second issue - I don't know how to easily give you more information on that, so I'll try describing the problem. When on a multiplayer server, using a weapon such as the widowmaker or the rocket launcher, when I press and hold down fire, it shoots extremely quickly even without any upgrades - at about 0.3 seconds per shot. Looking at the attack cooldown animation in the hotbar, it is clear that when held down, it completely ignores the cooldown proper, and prematurely fires. The speed is identical across all weapons meant to be (relatively) single shot, such as rocket launchers and shotguns.

**Comment by DarkwarriorJ** [comment]
Precise reason for the issue has been discovered. A different mod, cyberware, gives the relfex enhancer which doubles attacking speed with melee weapons. As your weapons are based off the melee cooldown, it also precisely doubled your mod's firing speeds. Not your problem.
