### ISSUE TITLE
Suggestion: 3D models

### ISSUE THREAD

**Issue by darthvader45** [rafradek/Mods#6]
I still have 3D models on my comp if you need em, and I can even make them still.  College classes will slow me down considerably, but I may still be able to pump a few out.  Let me know.  Just doing the basic stock weapons for now.

**Comment by rafradek** [comment]
Could you please send me how the models would look, since you know, there are already a few 3d models

**Comment by darthvader45** [comment]
https://www.dropbox.com/s/i09nh2bg9u7z8wr/TF2WeaponModels.zip?dl=0
https://www.dropbox.com/s/a0ru6redvgfptiv/TF2WeaponPics.zip?dl=0

Models and pics are here.

**Comment by rafradek** [comment]
Sadly, I would have to reject those models, since there are already better in the game. Also it looks like the weapon models are not in Json format.

**Comment by rafradek** [comment]
I can't show them now, just download version 1.0 at least
