### ISSUE TITLE
[1.12.1] [1.1.11.5] Server crash when teleporting across dimensions

### ISSUE THREAD

**Issue by Theray070696** [rafradek/Mods#7]
When using either a teleporter or the Eureka Effect to teleport across a dimension (nether to overworld, overworld to end, etc), the server will crash.

Crash log: https://pastebin.com/gg86R87F
Relevant part of latest.log: https://pastebin.com/jdsPFmG2

**Comment by Theray070696** [comment]
Line 86 of EntityTeleporter is
`entityIn.changeDimension(exit.dimension);`
A proper way to do it would be to use a custom Teleporter for non-item entities.
I have some code that already does this for 1.10 and 1.12.
[Link to relevant code in block](https://github.com/Theray070696/Mario-Mod-2/blob/master/src/main/java/io/github/Theray070696/mario2/block/BlockPipe.java#L122) (Please ignore my spaghetti code, onEntityCollidedWithBlock is only function that's relevant in this class. inPipeTime can also be ignored as Teleporters currently aren't two-way)
[Link to Teleporter class](https://github.com/Theray070696/Mario-Mod-2/blob/master/src/main/java/io/github/Theray070696/mario2/util/MarioTeleporter.java) (This can almost be copied verbatim)

I can make a pull request for this if you would like

**Comment by rafradek** [comment]
It's almost  exactly what have I done in several hours ago. You can expect a patch soon

**Comment by Theray070696** [comment]
Awesome! :D
