### ISSUE TITLE
Server crash upon putting Baseballs into an ammo furnace

### ISSUE THREAD

**Issue by triggerhurt** [rafradek/Mods#8]
Title says it all.
Crash log:
https://gist.github.com/triggerhurt/8e9dc06a20152504f7479c8c55c84c82
Edit:
I would also like to mention that I have no clue how ammo furnaces work. Their name should be self-explanatory, but they don't work consistently, or even much at all. At random, it seemed to smelt a single syringe, and then refused to smelt the rest.

**Comment by rafradek** [comment]
Fixed
